version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/code/cli/ytproc"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "pip"
      include: "scope"

  # Go dependencies
  - package-ecosystem: "gomod"
    directory: "/code/cli/ytproc"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "go"
      include: "scope"
